export const KasaModel = {
  SubeId: "",
  programData: [],
  data: [],
  VegaKasa: [],
};

export const DefaultKasa = {
  SubeId: "",
  YKSodexo: 0,
  YKTicket: 0,
  toplamGelenYemekCeki: 0,
  programYemekCeki: 0,
  YKDiger: 0,
  data: [],
  YKFark: 0,
  Nakit: 0,
  programNakit: 0,
  nakitFark: 0,
  Visa: 0,
  programVisa: 0,
  visaFark: 0,
  kontrol: 0,
  iadeAciklama: "",
  iadeIptal: 0,
  VegaKasa: [],
};

export const DetailKasa = {
  Nakit: 0,
  IadeAciklama: "",
  Sodexo: 0,
  YKSodexo: 0,
  YKTicket: 0,
  YKDiger: 0,
  YKFark: 0,
  NakitFark: 0,
  IadeIptal: 0,
  Kontrol: 0,
  ProgramYemekCeki: 0,
  ToplamGelenYemekCeki: 0,
  ProgramNakit: 0,
  Visa: 0,
  YemekCeki: 0,
  VisaFark: 0,
  YemekCekiAltToplam: 0,
  ToplamMultinet: 0,
  ToplamCioKart: 0,
  ToplamMetropol: 0,
  ToplamTicket: 0,
  ToplamSodexo: 0,
  ToplamSetCard: 0,
  Sonuc: 0,
  ToplamMasraf: 0,
  ToplamIade: 0,
  ToplamProgramNakit: 0,
  ToplamProgramVisa: 0,
  ToplamProgramYemekCeki: 0,
  VegaKasa: [],
};

export const TotalKasa = {
  Nakit: 0,
  Credit: 0,
  Multinet: 0,
  Ticket: 0,
  Sodexo: 0,
  SetCard: 0,
  Cio: 0,
  Metropol: 0,
  Diger: 0,
  YanToplam: 0,
  AltToplam: 0,
};

export const UrunBazliSatisModel = {
  data: [],
};
